### ISSUE TITLE
Origen de los datos...

### ISSUE THREAD

**Issue by Villanuevand** [abr4xas/bancos-json#2]
¿El listado de bancos es extraido del portal de la [Asociación Bancaria de Venezuela](https://www.asobanca.com.ve)?

**Comment by abr4xas** [comment]
No, por lo que estoy viendo... La data que hay en los pdf que están publicados es la contabilidad del banco en cuestión.

**Comment by Villanuevand** [comment]
Podemos verificar cuales de los bancos existentes en el archivo hacen concordancia con los expuestos en el portal de la asociación bancaria de venezuela.

**Comment by Villanuevand** [comment]
He realizado un [pequeño script](https://gist.github.com/Villanuevand/7f038574666b56ff8dc3), para obtener todos los bancos del listado que se encuentra en el sitio de la [Asociación de Bancaría de Venezuela](https://www.asobanca.com.ve/site/home.php). 

Ojalá sea de utilidad! 
_Instrucciones de uso en el gist!_

**Comment by abr4xas** [comment]
Fino!! :D ya lo estoy revisando :D

**Comment by abr4xas** [comment]
Esto funciono correctamente :+1: Gracias!!
